<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FlowPilot.Application\FlowPilot.Application.csproj" />
    <ProjectReference Include="..\..\src\FlowPilot.Database\FlowPilot.Database.csproj" />
    <ProjectReference Include="..\..\src\FlowPilot.Domain\FlowPilot.Domain.csproj" />
    <ProjectReference Include="..\..\src\FlowPilot.Infrastructure\FlowPilot.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
